services:
  hadeul-home:
    build:
      context: .
      args:
        CACHE_BUST: ${CACHE_BUST:-default}
    container_name: hadeul_home
    restart: unless-stopped
    ports:
      - "7080:3000"
    environment:
      - NODE_ENV=production
